[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libf = { path = "../libf" }
nom = "7"
cookie-factory = "0.3.2"